### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by iskakoff** [Green-Phys/.github#2]
- Setup web-address
- Decide on web interface engine (github-pages vs mediawiki)

**Comment by egull** [comment]
we own green-phys.org. http://green-phys.org/ now points to green-phys.github.io, and we have a sample index.html file there.

**Comment by egull** [comment]
The webpages are now online and properly encrypted with https. @iskakoff , I'll hand off to you for content...

**Comment by iskakoff** [comment]
migrated all documentation to github pages and we now use hugo engine for static content generation
